version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: anthony1
      MONGO_INITDB_ROOT_PASSWORD: 12345
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
